### ISSUE TITLE
可以使用微信公众测试号吗？

### ISSUE THREAD

**Issue by laorient** [myvas/AspNetCore.WeixinOAuth#1]
我申请了一个测试号，但是总是收到"Oops, something is wrong". 不知道该如何配置URL和Token。（使用的Demo程序）。

**Comment by huangxiangyao** [comment]
好消息！现在可以在.netcore 2.0下工作了，请参考Demo程序。

1.Demo程序部署在：http://weixinoauth.myvas.com

2.测试号二维码在这里：http://mmbiz.qpic.cn/mmbiz_jpg/lPe5drS9euRQR1eCK5cGXaibHYL6vBR4pGLB34ju2hXCiaMQiayOU8w5GMfEH7WZsVNTnhLTpnzAC9xfdWuTT89OA/0
测试人员须扫码关注这个公众号。

3.配置文件：appsettings.json，或secrets.json，后者若有配置则替换前者。
{
  "WeixinOAuth:AppId": "wx02056e2b2b9cc4ef",
  "WeixinOAuth:AppSecret": "c175a359cd383213906bc3aa346fff2f"
}

4.微信公众号配置

4.1.当使用公众平台测试账号时：开发/开发者工具/公众平台测试号/进入/...
（1）开通功能：网页服务/网页授权获取用户基本信息。
（2）设置好授权回调页面域名（例如weixinoauth.myvas.com）。

4.2.当使用正式平台账号时：/开发/接口权限/...
（1）开通功能：/网页服务/网页授权获取用户基本信息。
（2）设置好网页授权域名（例如weixinoauth.myvas.com）。
（3）将文件MP_verify_xxxxxxxxx.txt上传至wwwroot目录下。

5.测试工具：微信开发者工具 v1.01.1711160
下载地址：https://mp.weixin.qq.com/debug/wxadoc/dev/devtools/download.html

非常感谢您的关注！

**Comment by huangxiangyao** [comment]
从4.1开始，原WeixinOAuth拆分为两个：
（1）WeixinAuth：用于微信公众平台上申请的微信公众号，通常为微信页面提供授权。客户使用微信内置浏览器打开微信网页时，由程序自动完成身份验证，并通过补充其他必要的资料后自动提升用户权限（例如：匿名->提供手机号码->发起雇员身份确认->...）
（2）WeixinOpen：用于微信开放平台上申请的账号，登记开通网页应用接入配置后，通过微信扫码的方式实现身份验证。

演示网站：http://demo.auth.myvas.com
