### ISSUE TITLE
System.Exception: Correlation failed.'.AspNetCore.Correlation.Weixin-OAuth.-5Hw0bf0iYQ8KiF3xoCOyomRXTxU0j2n41-PEM1h8Z0' cookie not found.

### ISSUE THREAD

**Issue by laorient** [myvas/AspNetCore.WeixinOAuth#2]
We are getting this error when the user is a new one who never subscribed to the public account. The very first time they access the web page, this exception is thrown. I compared the code between WeixinOauthHandler.cs vs. the standard OAuthHandler.cs in aspnet/Security and see your code has the following: 

            var stateCookieName = ConcateCookieName(state);
            var protectedProperties = Request.Cookies[stateCookieName];
            if (string.IsNullOrEmpty(protectedProperties))
            {
                var errMsg = $"'{stateCookieName}' cookie not found.";
                Logger.LogWarning(errMsg);
                return HandleRequestResult.Fail("Correlation failed." + errMsg);
            }

And it is this block which is causing the problem. In the standard one, it is not relying on the cookie, only state. I can see that you are trying to circumvent the 128 bytes limitation of the WeixinOath State.
Why is it the case and how to solve the problem?

**Comment by huangxiangyao** [comment]
AspNetCore.WeixinAuth v4.1.2 fixed this bug, sorry for long time:

Cause: 
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1421140842
This 'state' limit of 128 bytes was defined by the Company Tencent.

Solution: (Naive, but works!)
We use a cookie to save the protected properties, and change the purpose of state to point the cookie name:
".AspNetCore.Correlation.{Scheme}.{CorrelationId}.N={ProtectedProperties}"
(1) Create/Protect: BuildChallengeUrl
(2) Unprotect/Delete: HandleChallengeAsync

Thank you for you patience.

PS.
(1) WeixinAuth is for mp.weixin.qq.com, to challenge in the MicroMessenger (aka Weixin/WeChat) builtin browser.
(2) WeixinOpen is for open.weixin.qq.com, to challenge in a common browser on PC or Mobile devices.
